### ISSUE TITLE
Probable missing file

### ISSUE THREAD

**Issue by expobrain** [sztanko/exaquery#10]
Are we missing a file in the repo here?

```
 FAIL  src/modules/ChannelBuilder.test.js
  ● Test suite failed to run

    Cannot find module './last_96h.js' from 'ChannelBuilder.test.js'

      1 | import addChannelInfo from "./ChannelBuilder";
      2 | import {expect} from "chai";
    > 3 | import large_data from "./last_96h.js"
        | ^
      4 |
      5 | const data = [
      6 |   {

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (src/modules/ChannelBuilder.test.js:3:1)
```

**Comment by sztanko** [comment]
Yes, and probably cannot be added due to privacy reasons.

I will create a PR that removes the tests with large_data.

**Comment by sztanko** [comment]
Fixed in https://github.com/sztanko/exaquery/pull/13
